export const LOGIN_USER = 'LOGIN_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const QUERY_EMPLOYEE = 'QUERY_EMPLOYEE';
export const QUERY_EMPLOYEE_FULFILLED = 'QUERY_EMPLOYEE_FULFILLED';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGOUT_USER_FULFILLED = 'LOGOUT_USER_FULFILLED';
